async_upload = true
bucket_no_upscale = true
bucket_reso_steps = 64
cache_latents = true
cache_latents_to_disk = true
caption_extension = ".txt"
clip_skip = 1
dynamo_backend = "no"
enable_bucket = true
epoch = 0
gradient_accumulation_steps = 2
gradient_checkpointing = true
huber_c = 0.0
huber_schedule = "snr"
huggingface_path_in_repo = "checkpoint"
huggingface_repo_id = ""
huggingface_repo_type = "model"
huggingface_repo_visibility = "public"
huggingface_token = ""
loss_type = "l2"
lr_scheduler = "cosine_with_restarts"
lr_scheduler_num_cycles = 1
lr_scheduler_args = ["warmup_steps", "50"]
lr_scheduler_power = 1
max_bucket_reso = 2048
max_data_loader_n_workers = 1
max_grad_norm = 1
max_timestep = 1000
max_token_length = 75
max_train_steps = 500
min_bucket_reso = 256
min_snr_gamma = 0
mixed_precision = "bf16"
network_alpha = 32
network_args = ["target_modules", "['to_q','to_k','to_v','proj_out']"]
network_dim = 64
network_module = "networks.lora"
no_half_vae = false
noise_offset_type = "v2"
learning_rate = 5e-5
optimizer_type = "AdamW8Bit"
optimizer_args = [
   "beta1", "0.9",
   "beta2", "0.999",
   "eps", "1e-08",
   "weight_decay", "0.01"
]
output_dir = "/app/outputs"
output_name = "last"
pretrained_model_name_or_path = "stabilityai/stable-diffusion-xl-base-1.0"
prior_loss_weight = 1
resolution = "1024,1024"
sample_prompts = ""
sample_sampler = "euler_a"
save_every_n_epochs = 0
save_model_as = "safetensors"
save_precision = "bf16"
scale_weight_norms = 5
text_encoder_lr = 0.00001
train_batch_size = 16
train_data_dir = ""
training_comment = ""
unet_lr = 0.00001
xformers = true